### create a new instance of User.
POST {{url}}/auth/users/
accept: application/json
Content-Type: application/json

{
  "first_name": "moon1",
  "last_name": "moon1",
  "email": "moon1@m.com",
  "password": "12345@mn",
  "username": "moon1"
}

### Get current user information
GET {{url}}/auth/users/me
accept: application/json
Authorization: JWT {{user_2_access}}

### Create a wallet account
POST {{url}}/api/wallet/
accept: application/json
Authorization: JWT {{admin_access}}

{
  "user": 2,
  "money": 20000
}

###
GET {{url}}/api/wallet/
accept: application/json
Authorization: JWT {{user_2_access}}

###
POST {{url}}/api/wallet/3/charge
accept: application/json
Authorization: JWT {{user_2_access}}

{
  "user": 4,
  "money": 5000
}

###
POST {{url}}/api/wallet/{{wallet_id}}/purchase/
accept: application/json
Authorization: JWT {{user_2_access}}

{}