### get list of tickets
GET {{url}}/api/ticket/
accept: application/json
Authorization: JWT {{user_2_access}}


### reseve tickets.
PUT {{url}}/api/ticket/12/reserve/
accept: application/json
Authorization: JWT {{user_2_access}}

{
  "id": 1,
  "created_at": "2024-01-26T12:25:27.947535Z",
  "status": 4,
  "price": 9,
  "user": 100,
  "match": 1,
  "seat": 6,
  "stadium": 4
}


### get list of tickets
GET {{url}}/api/ticket/11/
accept: application/json
Authorization: JWT {{user_2_access}}
