version: '3'

services:
#  django:
#    build:
#      context: .
#      dockerfile: Dockerfile
#    container_name: django-container
#    ports:
#      - "8000:8000"
#    depends_on:
#      - redis


  redis:
    image: redis
    container_name: redis-container
    ports:
      - "6379:6379"

  db:
    image: postgres:12.4
    container_name: postgres-container
    environment:
      POSTGRES_DB: "selling_platform_db"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data


  worker:
    build:
      context: .
      dockerfile: Dockerfile.celery
    container_name: celery-worker
    environment:
      - BROKER_URL=redis://redis:6379/0
      - RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - redis
      - db
  flower:
    image: mher/flower:0.9.7
    command: ['flower', '--broker=redis://redis:6379', '--port=5555']
    ports:
      - "5557:5555"
    depends_on:
      - redis


volumes:
  postgres_data: