# Celery Dockerfile
FROM python:3.10

WORKDIR /app

COPY requirements.txt /app/
RUN pip install --no-cache-dir -r requirements.txt

COPY . /app/

# Replace CMD with the desired command
CMD ["celery", "-A", "seats", "worker", "-l", "info", "-P", "gevent", "-E"]