version: '3'

services:
#  django:
#    build:
#      context: .
#      dockerfile: Dockerfile
#    container_name: django-container
#    ports:
#      - "8000:8000"
#    depends_on:
#      - redis


  redis:
    image: redis
    container_name: redis-container
    ports:
      - "6379:6379"

  worker:
    build:
      context: .
      dockerfile: Dockerfile.celery
    container_name: celery-worker
    environment:
      - BROKER_URL=redis://redis:6379
      - RESULT_BACKEND=redis://redis:6379
    depends_on:
      - redis

  flower:
    image: mher/flower:0.9.7
    command: ['flower', '--broker=redis://redis:6379', '--port=5555']
    ports:
      - "5557:5555"
    depends_on:
      - redis
